name: ElementPlugin
version: '1.0-SNAPSHOT'
main: hs.elementPlugin.ElementPlugin
api-version: '1.21'
load: STARTUP
authors: [ ___Pumpkinn ]

commands:
  trust:
    description: Manage trust relationships
    usage: /trust <list|add|remove|accept|deny> [player]
    permission: element.trust

  element:
    description: Element admin/self commands
    usage: /element <reroll|set> [player] <air|water|fire|earth|life>
    permission: element.element

  mana:
    description: Manage mana (reset or set)
    usage: /mana <reset|set> [player] [amount]
    permission: element.mana
