name: ElementPlugin
version: '1.1.16'
main: saturn.elementPlugin.ElementPlugin
website: https://ko-fi.com/1pumpkinn
api-version: '1.21.8'
load: STARTUP
authors: [ ___Pumpkinn ]
contributors: [ ___Vishini ]

commands:
  trust:
    description: Manage individual trust relationships
    usage: /trust <list|accept|deny|remove> [player]

  team:
    description: Manage team relationships and customization
    usage: /team <create|invite|accept|leave|kick|disband|color|bold|italic> [args]

  element:
    description: Element admin commands
    usage: /element <set|debug> <player> [element]
    permission: element.admin

  mana:
    description: Manage mana (reset or set)
    usage: /mana <reset|set> [player] [amount]
    permission: element.mana

  data:
    description: Manage plugin data storage
    usage: /data <save|backup|stats>
    permission: element.admin

  util:
    description: Get utility items (upgraders and reroller)
    usage: /util
    permission: element.admin

  damagetest:
    description: Protection 4 Villager
    permission: element.admin

  elements:
    description: View information about all elements
    usage: /elements [element_name]
    aliases: [ elementinfo, elinfo ]

permissions:
  element.admin:
    description: Allows use of element admin commands
    default: op

  element.mana:
    description: Allows use of mana management commands
    default: op

