name: ElementPlugin
version: '1.2.0'
main: saturn.elementPlugin.ElementPlugin
website: https://ko-fi.com/1pumpkinn
api-version: '1.21.10'
load: STARTUP
authors: [ ___Pumpkinn ]
contributors: [ ___Vishini ]

commands:
  team:
    description: Manage teams, allies, and customization
    usage: /team <create|invite|accept|leave|kick|disband|ally|color|bold|italic|list|hide|unhide> [args]

  element:
    description: Element admin commands
    usage: /element <set|debug> <player> [element]
    permission: element.admin

  mana:
    description: Manage mana (reset or set)
    usage: /mana <reset|set> [player] [amount]
    permission: element.mana

  data:
    description: Manage plugin data storage
    usage: /data <save|backup|stats>
    permission: element.admin

  util:
    description: Get utility items (upgraders and reroller)
    usage: /util
    permission: element.admin

  damagetest:
    description: Protection 4 Villager
    permission: element.admin

  elements:
    description: View information about all elements
    usage: /elements [element_name]
    aliases: [ elementinfo, elinfo ]

  disableabilities:
    description: Manage regions where abilities are disabled
    usage: /disableabilities <pos1|pos2|create|remove|list|info|reload> [args]
    aliases: [ disableability, disableab ]
    permission: element.admin

permissions:
  element.admin:
    description: Allows use of element admin commands
    default: op

  element.mana:
    description: Allows use of mana management commands
    default: op